var questions = [{
        "id": 1,
        "question": "驾驶人违反交通运输管理法规发生重大事故后，因逃逸致人死亡的，处多少年有期徒刑？",
        "answer": "4",
        "item1": "2年以下",
        "item2": "3年以下",
        "item3": "7年以下",
        "item4": "7年以上",
        "expalins": "要看清题目致人死亡的是不是因为逃逸造成的，如果是那就是7年以上。",
        "url": ""
    },
    {
        "id": 2,
        "question": "机动车仪表板上（如图所示）亮表示什么？",
        "answer": "1",
        "item1": "防抱死制动系统故障",
        "item2": "驻车制动器处于解除状态",
        "item3": "行车制动系统故障",
        "item4": "安全气囊处于故障状态",
        "expalins": "ABS就是防抱死制动系统",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1122.jpeg"
    },
    {
        "id": 3,
        "question": "这个标志是何含义？",
        "answer": "4",
        "item1": "高速公路救援电话号码",
        "item2": "高速公路服务电话号码",
        "item3": "高速公路报警电话号码",
        "item4": "高速公路交通广播频率",
        "expalins": "高速公路交通广播频率：用以指示收听高速公路或城市快速路交通信息广播的频率，可在适当地点设置，根据需要可重复设置。查看高速公路标志大全：http://www.jszks.com/onepage/16721.html",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_81.jpg"
    },
    {
        "id": 4,
        "question": "提供虚假材料申领驾驶证的申请人会承担下列哪种法律责任？",
        "answer": "3",
        "item1": "处20元以上200元以下罚款",
        "item2": "取消申领驾驶证资格",
        "item3": "1年内不得再次申领驾驶证",
        "item4": "2年内不能再次申领驾驶证",
        "expalins": "《机动车驾驶证申领和使用规定》（公安部令第123号）第七十八条  隐瞒有关情况或者提供虚假材料申领机动车驾驶证的，申请人在一年内不得再次申领机动车驾驶证。",
        "url": ""
    },
    {
        "id": 5,
        "question": "驾驶机动车需要在路边停车时怎样选择停车地点？",
        "answer": "2",
        "item1": "靠左侧路边逆向停放",
        "item2": "在停车泊位内停放",
        "item3": "在路边随意停放",
        "item4": "在人行道上停放",
        "expalins": "只有停车泊位是可以停放的。",
        "url": ""
    },
    {
        "id": 6,
        "question": "机动车在紧急制动时ABS系统会起到什么作用？",
        "answer": "4",
        "item1": "切断动力输出",
        "item2": "自动控制方向",
        "item3": "减轻制动惯性",
        "item4": "防止车轮抱死",
        "expalins": "ABS通过控制作用于车轮制动分泵上的制动管路压力，使汽车在紧急刹车时车轮不会抱死，故选D。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_498.jpg"
    },
    {
        "id": 7,
        "question": "交通肇事致一人以上重伤，负事故全部或者主要责任，并具有下列哪种行为的，构成交通肇事罪?",
        "answer": "3",
        "item1": "未带驾驶证",
        "item2": "未报警",
        "item3": "无驾驶资格驾驶机动车辆的",
        "item4": "未抢救受伤人员",
        "expalins": "可能构成交通壁事罪。例如，交通壁事致一人受伤(属于一般事故)，负事故全部或者主要责任，并具有酒后、无证驾驶、严重超载等情形之一的，以交通肇事罪处罚。",
        "url": ""
    },
    {
        "id": 8,
        "question": "如图所示，驾驶机动车遇到这种情况时，以下做法正确的是什么？ ",
        "answer": "2",
        "item1": "应减速观察水情，然后加速行驶通过",
        "item2": "应停车察明水情，确认安全后，低速通过",
        "item3": "应停车察明水情，确认安全后，快速通过",
        "item4": "可随意通行",
        "expalins": "机动车在有积水较深的桥下通过行车时，应当停车察明水情，确认安全后，低速通过。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_914.jpg"
    },
    {
        "id": 9,
        "question": "在山区道路遇对向来车时，应怎样会车？",
        "answer": "4",
        "item1": "紧靠道路中心",
        "item2": "不减速",
        "item3": "加速",
        "item4": "减速或停车让行",
        "expalins": "是双方选择怎么交会，两个车可以等到安全路段再减速交会",
        "url": ""
    },
    {
        "id": 10,
        "question": "这个标志是何含义？",
        "answer": "2",
        "item1": "向左单行路",
        "item2": "向右单行路",
        "item3": "直行单行路",
        "item4": "右转让行",
        "expalins": "表示一切车辆向右单向行驶。此标志设在单行路的路口和入口处的适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_107.jpg"
    },
    {
        "id": 11,
        "question": "这一组交通警察手势是什么信号？",
        "answer": "4",
        "item1": "减速慢行信号",
        "item2": "靠边停车信号",
        "item3": "停止信号",
        "item4": "右转弯信号",
        "expalins": "手势题详解：http://www.jszks.com/onepage/16203.html",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_130.jpg"
    },
    {
        "id": 12,
        "question": "有下列哪种违法行为的机动车驾驶人将被一次记6分？",
        "answer": "1",
        "item1": "驾驶机动车违反道路交通信号灯",
        "item2": "未取得校车驾驶资格驾驶校车",
        "item3": "驾驶与准驾车型不符的机动车",
        "item4": "饮酒后驾驶机动车",
        "expalins": "闯灯的一次6分。B,C,D都是一次记12分。",
        "url": ""
    },
    {
        "id": 13,
        "question": "上道路行驶的机动车故意遮挡、污损、不按规定安装机动车号牌的一次记几分？",
        "answer": "4",
        "item1": "2分",
        "item2": "3分",
        "item3": "6分",
        "item4": "12分",
        "expalins": "上道路行驶的机动车未悬挂机动车号牌的，或者故意遮挡、污损、不按规定安装机动车号牌的一次记12分。",
        "url": ""
    },
    {
        "id": 14,
        "question": "在山区道路超车时，应怎样超越？",
        "answer": "2",
        "item1": "抓住任何机会尽量",
        "item2": "选择宽阔的缓上坡路段",
        "item3": "选择较长的下坡路",
        "item4": "选择较缓的下坡路",
        "expalins": "上坡有阻力，不宜滑车，也不宜撞车，所以上坡宽阔地可以超车！",
        "url": ""
    },
    {
        "id": 15,
        "question": "准驾车型为小型自动挡汽车的，可以驾驶以下哪种车型？",
        "answer": "4",
        "item1": "低速载货汽车",
        "item2": "小型汽车",
        "item3": "二轮摩托车",
        "item4": "轻型自动挡载货汽车",
        "expalins": "小型自动挡汽车（C2）准驾车型：小型、微型自动挡载客汽车以及轻型、微型自动挡载货汽车",
        "url": ""
    },
    {
        "id": 16,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "旅游区距离",
        "item2": "旅游区类别",
        "item3": "旅游区方向",
        "item4": "旅游区符号",
        "expalins": "快到云居寺了，箭头指的是方向",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_196.jpg"
    },
    {
        "id": 17,
        "question": "机动车仪表板上（如图所示）这个符号表示什么？",
        "answer": "2",
        "item1": "行李舱开启",
        "item2": "发动机舱开启",
        "item3": "燃油箱盖开启",
        "item4": "一侧车门开启",
        "expalins": "前盖为发动机舱，后边为行李舱。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_559.jpeg"
    },
    {
        "id": 18,
        "question": "指示标志的作用是什么？",
        "answer": "4",
        "item1": "告知方向信息",
        "item2": "警告前方危险",
        "item3": "限制车辆、行人通行",
        "item4": "指示车辆、行人行进",
        "expalins": "指示标志是交通标志中主要标志的一种，用以指示车辆和行人按规定方向、地点行驶。 指示标志的颜色为蓝底、白图案；形状分为圆形、长方形和正方形。",
        "url": ""
    },
    {
        "id": 19,
        "question": "机动车仪表板上（如图所示）这个符号表示什么？",
        "answer": "3",
        "item1": "远光灯开关",
        "item2": "近光灯开关",
        "item3": "车灯总开关",
        "item4": "后雾灯开关",
        "expalins": "此为车灯总开关。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_738.jpeg"
    },
    {
        "id": 20,
        "question": "存在以下哪种行为的申请人在一年内不得再次申领机动车驾驶证？",
        "answer": "2",
        "item1": "在考试过程中出现身体不适",
        "item2": "在考试过程中有舞弊行为",
        "item3": "不能按照教学大纲认真练习驾驶技能",
        "item4": "未参加理论培训",
        "expalins": "《机动车驾驶证申领和使用规定》第六章，法律责任，第七十八条，隐瞒有关情况或者提供虚假材料申领机动车驾驶证的，申请人在一年内不得再次申领机动车驾驶证。申请人在考试过程中有贿赂、舞弊行为的，取消考试资格，已经通过考试的其他科目成绩无效；申请人在一年内不得再次申领机动车驾驶证。",
        "url": ""
    },
    {
        "id": 21,
        "question": "这个标志是何含义？",
        "answer": "2",
        "item1": "路面不平",
        "item2": "路面低洼",
        "item3": "路面高突",
        "item4": "有驼峰桥",
        "expalins": "路面低洼：用以提醒车辆驾驶人减速慢行。设在路面突然低洼以前适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_858.jpg"
    },
    {
        "id": 22,
        "question": "图中圈内的锯齿状白色实线是什么标线？",
        "answer": "3",
        "item1": "导向车道线",
        "item2": "方向引导线",
        "item3": "可变导向车道线",
        "item4": "单向行驶线",
        "expalins": "这道儿左转右转还是直行都是可以的，关键看信号灯或者路面上的指标牌",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_364.jpg"
    },
    {
        "id": 23,
        "question": "上道路行驶的机动车未悬挂机动车号牌的一次记几分？",
        "answer": "2",
        "item1": "6分",
        "item2": "12分",
        "item3": "2分",
        "item4": "3分",
        "expalins": "上道路行驶的机动车未悬挂机动车号牌的，或者故意遮挡、污损、不按规定安装机动车号牌的一次记12分。",
        "url": ""
    },
    {
        "id": 24,
        "question": "山区道路对安全行车的主要影响是什么？",
        "answer": "2",
        "item1": "交通情况单一",
        "item2": "坡长弯急，视距不足",
        "item3": "车流密度大",
        "item4": "道路标志少",
        "expalins": "最关键的一点是山区道路行驶时不容易掌握周围情况，也就是所谓视距不足。",
        "url": ""
    },
    {
        "id": 25,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "注意双向行驶",
        "item2": "靠两侧行驶",
        "item3": "注意潮汐车道",
        "item4": "可变车道",
        "expalins": "“潮汐车道”是指根据早晚交通流量不同情况，对有条件的道路，试点开辟潮汐车道，通过车道灯的指示方向变化，控制主干道车道行驶方向，来调整车道数。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_33.jpg"
    },
    {
        "id": 26,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "人行横道灯",
        "item2": "注意行人",
        "item3": "注意信号灯",
        "item4": "交叉路口",
        "expalins": "注意信号灯：用以警告车辆驾驶人注意前方路段设有信号灯，应依信号灯指示行车。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_401.jpg"
    },
    {
        "id": 27,
        "question": "夜间车辆通过照明条件良好的路段时，应使用什么灯？",
        "answer": "3",
        "item1": "危险报警闪光灯",
        "item2": "远光灯",
        "item3": "近光灯",
        "item4": "雾灯",
        "expalins": "直接解释大家可能难以转过弯来，我们先反过来看这题！夜间车辆通过照明条件不良好的路段时应使用--? 答案：远光灯。照明不良好就是看不见远近路段，当然是打开远光灯，看的更远更清楚，相反照明良好时，也就是说远近处，我们都能看的见，当然是打开近光灯最为保险。",
        "url": ""
    },
    {
        "id": 28,
        "question": "驾驶机动车在没有道路中心线的狭窄山路怎样会车？",
        "answer": "1",
        "item1": "不靠山体的一方先行",
        "item2": "靠山体的一方先行",
        "item3": "重车让空车先行",
        "item4": "速度慢的先行",
        "expalins": "山路狭窄，这种山路一般有在靠山体一侧挖个让车位，说白了就是加宽点用来会车用的，两车交会时靠山的开进去停住，不一定有落石的， 让不靠山体车先行，是不会开到路边去的，总不能不靠山的停下来，靠山的车转弯进去再转弯出来吧，这要加宽多长哦，这样子的话就不叫狭窄山路了。",
        "url": ""
    },
    {
        "id": 29,
        "question": "同车道行驶的车辆前方遇到下列哪种车辆不得超车？",
        "answer": "3",
        "item1": "大型客货车",
        "item2": "出租汽车",
        "item3": "执行任务的救护车",
        "item4": "公共汽车",
        "expalins": "亲，人命关天，您就别超了。",
        "url": ""
    },
    {
        "id": 30,
        "question": "如图所示，驾驶机动车行驶至车道减少的路段时，遇前方机动车排队等候或行驶缓慢时，以下做法正确的是什么？",
        "answer": "2",
        "item1": "右侧车让左侧车先行",
        "item2": "每车道一辆依次交替驶入左侧车道",
        "item3": "左侧车让右侧车先行",
        "item4": "右侧车寻找空隙提前进入左侧车道",
        "expalins": "驾驶机动车行驶至车道减少的路段时，前方机动车排队等候或行驶缓慢时，应当每车道一辆依次交替驶入左侧车道。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_951.jpg"
    },
    {
        "id": 31,
        "question": "路两侧的车行道边缘白色实线是什么含义？",
        "answer": "2",
        "item1": "车辆可临时跨越",
        "item2": "禁止车辆跨越",
        "item3": "机动车可临时跨越",
        "item4": "非机动车可临时跨越",
        "expalins": "白虚线不可以跨越",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_114.jpg"
    },
    {
        "id": 32,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "两侧通行",
        "item2": "右侧通行",
        "item3": "左侧通行",
        "item4": "不准通行",
        "expalins": "用于引导行车方向，提示道路使用者前方线形变化，注意谨慎驾驶。设于中央隔离设施端部、渠化设施的端部、桥头等。答题技巧：∧表示俩侧通行，/这个方向的表示左侧通行，这个方向表示右侧通行。交通指路标志大全：http://www.jszks.com/onepage/16752.html",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_249.jpg"
    },
    {
        "id": 33,
        "question": "这个标志是何含义？",
        "answer": "1",
        "item1": "车道数变少",
        "item2": "合流处",
        "item3": "应急车道",
        "item4": "向左变道",
        "expalins": "三车道变成二车道故车道数变少，选A。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_3.jpg"
    },
    {
        "id": 34,
        "question": "年满20周岁，可以初次申请下列哪种准驾车型？",
        "answer": "1",
        "item1": "大型货车.",
        "item2": "大型客车",
        "item3": "中型客车",
        "item4": "牵引车",
        "expalins": "申请城市公交车、大型货车、无轨电车或者有轨电车准驾车型的，在20周岁以上，50周岁以下；",
        "url": ""
    },
    {
        "id": 35,
        "question": "这个标志是何含义？",
        "answer": "4",
        "item1": "减速让行",
        "item2": "潮汐车道",
        "item3": "分离式道路",
        "item4": "双向交通",
        "expalins": "双向交通：用以提醒车辆驾驶人注意会车。设在由双向分离行驶，因某种原因出现临时性或永久性的不分离双向行驶的路段，或由单向行驶进人双向行驶的路段以前适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_124.jpg"
    },
    {
        "id": 36,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "高速公路右侧出口预告",
        "item2": "高速公路下一出口预告",
        "item3": "高速公路地点、方向预告",
        "item4": "高速公路左侧出口预告",
        "expalins": "高速公路地点、方向预告：用于指示高速公路或城市快速路两个行驶方向，设在驶入高速公路或城市快速路的匝道分岔点处。在目的地信息之上，可增加前往高速公路的编号信息。查看高速公路标志大全：http://www.jszks.com/onepage/16721.html",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_69.jpg"
    },
    {
        "id": 37,
        "question": "如图所示，在这起交通事故中，以下说法正确的是什么？ ",
        "answer": "1",
        "item1": "A车负全部责任",
        "item2": "B车负全部责任",
        "item3": "各负一半的责任",
        "item4": "B车负主要责任",
        "expalins": "这起交通事故主要是因为A车绕开障碍物时未提前观察减速为B车让行造成的，所以A车全责。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_789.jpg"
    },
    {
        "id": 38,
        "question": "路口最前端的双白实线是什么含义？",
        "answer": "1",
        "item1": "停车让行线",
        "item2": "减速让行线",
        "item3": "左弯待转线",
        "item4": "等候放行线",
        "expalins": "停车让行线是在没有信号灯状态下。停止线是遇有信号灯红灯时表示车辆等候放行信号的位置,不能超越或压此线。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_195.jpg"
    },
    {
        "id": 39,
        "question": "在这条车道行驶的最低车速是多少？",
        "answer": "4",
        "item1": "100公里/小时",
        "item2": "110公里/小时",
        "item3": "60公里/小时",
        "item4": "90公里/小时",
        "expalins": "高速路同方向有3条车道，最左侧的为110公里到120公里，中间的为90公里到110公里，最右侧的速度范围为60公里到90公里。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_190.jpg"
    },
    {
        "id": 40,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "直行和左转车道",
        "item2": "直行和辅路出口车道",
        "item3": "直行和右转合用车道",
        "item4": "分向行驶车道",
        "expalins": "表示只准一切车辆直行和向右转弯。此标志设在车辆必须直行和向右转弯）的路口以前适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_27.jpg"
    },
    {
        "id": 41,
        "question": "这个标志是何含义？",
        "answer": "1",
        "item1": "旅游区距离",
        "item2": "旅游区方向",
        "item3": "旅游区符号",
        "item4": "旅游区类别",
        "expalins": "遇此类标志是指旅游区的距离还有多远（亲不要激动 安全第一 慢行",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_167.jpg"
    },
    {
        "id": 42,
        "question": "驾驶机动车遇到这种信号灯不断闪烁时怎样行驶？",
        "answer": "3",
        "item1": "尽快加速通过",
        "item2": "靠边停车等待",
        "item3": "注意观望安全通过",
        "item4": "紧急制动",
        "expalins": "路口黄灯持续闪烁，警示驾驶人要注意�望，确认安全通过。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1153.jpg"
    },
    {
        "id": 43,
        "question": "如图所示，驾驶机动车遇到这种情况，以下做法正确的是什么？",
        "answer": "3",
        "item1": "长鸣喇叭催促行人快速通过",
        "item2": "开启远光灯警示行人有车辆驶近",
        "item3": "降低行驶速度，避让行人",
        "item4": "适当加速从行人前方绕行",
        "expalins": "驾驶机动车遇到图中这种情况，应当降低行驶速度，避让行人。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_959.jpg"
    },
    {
        "id": 44,
        "question": "如图所示，以下哪种情况可以超车?(图51a.51b. 51c. 51d)",
        "answer": "1",
        "item1": "51a",
        "item2": "51b",
        "item3": "51c",
        "item4": "51d",
        "expalins": "如图所示，能够超车的必须满足两个条件：一是必须在虚线的一侧，而是对向没有来车。满足这个两个条件的就只有51a了。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_777.jpg"
    },
    {
        "id": 45,
        "question": "这个标志是何含义？",
        "answer": "1",
        "item1": "距无人看守铁路道口150米",
        "item2": "距无人看守铁路道口100米",
        "item3": "距有人看守铁路道口100米",
        "item4": "距有人看守铁路道口150米",
        "expalins": "一道红线是50米，三道150米。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_39.jpg"
    },
    {
        "id": 46,
        "question": "以下哪种违法行为的机动车驾驶人将被一次记6分？",
        "answer": "3",
        "item1": "驾驶与准驾车型不符的机动车",
        "item2": "车速超过规定时速50%以上",
        "item3": "驾驶机动车违反道路交通信号灯",
        "item4": "未取得校车驾驶资格驾驶校车",
        "expalins": "机动车驾驶员有下列违章行为之一的，一次记6分:(一)不按规定停车或者车辆发生故障不立即将车移开，造成交通严重堵塞的；(二)逆向行驶的；(三)饮酒后驾驶车辆的；(四)驾车穿插、超越警车护卫的车队的；(五)驾驶与驾驶证准驾车型不相符合的车辆的；(六)驾车下陡坡时熄火、空挡滑行的；(七)行经铁路道口不按规定行车或者停车的；(八)客车载人超过核定人数20%以上的；(九)在高速公路上客车载人超过核定人数的；(十)在高速公路上货车载物超过核定载质量30%以上的；(十一)在高速公路上不按规定超车或者变更车道的；(十二)在高速公路上驾驶转向器、制动器、灯光装置等机件不符合安全要求的车辆的；(十三)在高速公路上载运危险物品未经审批或者未按规定行驶的。",
        "url": ""
    },
    {
        "id": 47,
        "question": "这个路面标记是什么标线？",
        "answer": "3",
        "item1": "禁驶区",
        "item2": "网状线",
        "item3": "中心圈",
        "item4": "导流线",
        "expalins": "中心圈，设置在交叉路口中心的白色圆形或菱形区域，用以区分车辆大、小转弯，及交叉路口车辆左右转弯的指示，车辆不得压线行驶。机动车向左转弯时，必须紧靠中心圈小转弯。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_720.jpg"
    },
    {
        "id": 48,
        "question": "如图所示，铁路道口禁止掉头的原因是什么？",
        "answer": "4",
        "item1": "有铁路道口标志",
        "item2": "有铁路道口信号灯",
        "item3": "铁路道口车流量大",
        "item4": "容易引发事故",
        "expalins": "铁道路口行车条件比较复杂，掉头容易引发事故。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_801.jpg"
    },
    {
        "id": 49,
        "question": "机动车仪表板上（如图所示）亮表示什么？",
        "answer": "4",
        "item1": "充电电流过大",
        "item2": "蓄电池损坏",
        "item3": "电流表故障",
        "item4": "充电电路故障",
        "expalins": "此为充电电路故障，一般没有故障这些都不会亮的，只有出故障了才会亮。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_746.jpeg"
    },
    {
        "id": 50,
        "question": "机动车驾驶人有以下哪种违法行为的，暂扣六个月机动车驾驶证？",
        "answer": "3",
        "item1": "醉酒后驾驶机动车的",
        "item2": "伪造、变造机动车驾驶证的",
        "item3": "饮酒后驾驶机动车的",
        "item4": "使用伪造、变造机动车驾驶证的",
        "expalins": "饮酒驾驶机动车辆，罚款1000元―2000元、记12分并暂扣驾照6个月；饮酒驾驶营运机动车，罚款5000元，记12分，处以15日以下拘留，并且5年内不得重新获得驾照。醉酒驾驶机动车辆，吊销驾照，5年内不得重新获取驾照，经过判决后处以拘役，并处罚金；醉酒驾驶营运机动车辆，吊销驾照，10年内不得重新获取驾照，终生不得驾驶营运车辆，经过判决后处以拘役，并处罚金。",
        "url": ""
    },
    {
        "id": 51,
        "question": "这个标志是何含义？",
        "answer": "4",
        "item1": "向右变道",
        "item2": "分流处",
        "item3": "路面变宽",
        "item4": "车道数增加",
        "expalins": "俩个车道变成三个，表示车道数增加。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_133.jpg"
    },
    {
        "id": 52,
        "question": "这个标志是何含义？",
        "answer": "2",
        "item1": "大型客车专用车道",
        "item2": "公交线路专用车道",
        "item3": "快速公交系统专用车道",
        "item4": "多乘员车辆专用车道",
        "expalins": "此为公交线路专用车道，与快速公交系统专用车道的区别是少了“快速公交”四个字。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_17.jpg"
    },
    {
        "id": 53,
        "question": "下长坡时，控制车速除了刹车制动以外还有什么有效的辅助方法？",
        "answer": "2",
        "item1": "挂入空挡滑行",
        "item2": "利用发动机制动",
        "item3": "关闭发动机熄火滑行",
        "item4": "踏下离合器滑行",
        "expalins": "发动机制动就是挂低档，让车利用低档位的惯性制动，你可以试一下，你在3挡的速度，直接挂1挡，记住不要踩刹车，直接挂档，你看效果如何，车身会震一下，速度下降的很快",
        "url": ""
    },
    {
        "id": 54,
        "question": "这个标志是何含义？",
        "answer": "1",
        "item1": "停车领卡",
        "item2": "停车缴费",
        "item3": "ETC通道",
        "item4": "停车检查",
        "expalins": "停车领卡：用以提示停车领卡，设在进入高速公路或城市快速路收费站入口一侧的适当位置。查看高速公路标志大全：http://www.jszks.com/onepage/16721.html",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_223.jpg"
    },
    {
        "id": 55,
        "question": "在这种路口怎样进行掉头？",
        "answer": "1",
        "item1": "从中心线虚线处掉头",
        "item2": "从右侧车道掉头",
        "item3": "进入路口后掉头",
        "item4": "在人行横道上掉头",
        "expalins": "从中心线虚线处是可以掉头的，其他的选项都不对。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_234.jpg"
    },
    {
        "id": 56,
        "question": "夜间驾驶机动车在窄路、窄桥会车怎样使用灯光？",
        "answer": "2",
        "item1": "关闭所有灯光",
        "item2": "开启近光灯",
        "item3": "关闭前照灯",
        "item4": "开启远光灯",
        "expalins": "记住，只有在没有路灯或者没有照明的情况下才能用远光灯，一般都用近光灯。",
        "url": ""
    },
    {
        "id": 57,
        "question": "驾驶车辆在交叉路口前变更车道时，应怎样驶入要变更的车道？",
        "answer": "4",
        "item1": "在路口前实线区内根据需要",
        "item2": "进入路口实线区内",
        "item3": "在路口停止线前",
        "item4": "在虚线区按导向箭头指示",
        "expalins": "当然是在未到人行道前按导向标识了，要不都到人行道边上了，怎么改变车道。",
        "url": ""
    },
    {
        "id": 58,
        "question": "这个标志是何含义？",
        "answer": "2",
        "item1": "右侧是下坡路段",
        "item2": "靠右侧道路行驶",
        "item3": "靠道路右侧停车",
        "item4": "只准向右转弯",
        "expalins": "靠右侧道路行驶：表示只准一切车辆靠右侧道路行驶。此标志设在车辆必须靠右侧行驶的路口以前适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_31.jpg"
    },
    {
        "id": 59,
        "question": "红色圆圈内标线含义是什么？",
        "answer": "2",
        "item1": "临时停靠站",
        "item2": "港湾式停靠站",
        "item3": "应急停车带",
        "item4": "公交车停靠站",
        "expalins": "请记住",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1097.jpg"
    },
    {
        "id": 60,
        "question": "这个标志是何含义？",
        "answer": "4",
        "item1": "十字交叉路口预告",
        "item2": "互通立体交叉预告",
        "item3": "Y型交叉路口预告",
        "item4": "环行交叉路口预告",
        "expalins": "环形交叉口是在几条相交道路的平面交叉口中央设置一个半径较大的中心岛，使所有经过交叉口的直行和左转车辆都绕着中心岛作逆时针方向行驶，在其行驶过程中将车流的冲突点变  为交织点，从而保证交叉口的行车安全，提高交叉口的通行能力。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_13.jpg"
    },
    {
        "id": 61,
        "question": "遇到前方车辆缓慢行驶时怎样行驶？",
        "answer": "1",
        "item1": "依次排队行驶",
        "item2": "占对向车道超越",
        "item3": "从右侧借道超越",
        "item4": "从两侧随意超越",
        "expalins": "请选最和谐的答案。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_395.jpg"
    },
    {
        "id": 62,
        "question": "年龄在60周岁以上的机动车驾驶人，应当每年进行一次身体检查的目的是什么？",
        "answer": "4",
        "item1": "体现对老年人的关心",
        "item2": "例行程序仅供参考",
        "item3": "检查是否患有老年常见病",
        "item4": "检查是否患有妨碍安全驾驶的疾病",
        "expalins": "根据《机动车驾驶证申领使用规定》第四十八条规定年龄在60周岁以上或者持有大型客车、牵引车、城市公交车、中型客车、大型货车、无轨电车、有轨电车准驾车型的机动车驾驶人，应当每年进行一次身体检查，在记分周期结束后十五日内，提交县级或者部队团级以上医疗机构出具的有关身体条件的证明，检查是否患有妨碍安全驾驶的疾病。",
        "url": ""
    },
    {
        "id": 63,
        "question": "在这段高速公路上行驶的最低车速是多少？",
        "answer": "3",
        "item1": "100公里/小时",
        "item2": "80公里/小时",
        "item3": "60公里/小时",
        "item4": "50公里/小时",
        "expalins": "图片上那个蓝色的牌子60就是最低车速。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_307.jpg"
    },
    {
        "id": 64,
        "question": "机动车在高速公路行驶，下列做法正确的是？",
        "answer": "1",
        "item1": "非紧急情况时不得在应急车道行驶或者停车",
        "item2": "可在减速车道或加速车道上超车、停车",
        "item3": "可在紧急停车带停车装卸货物",
        "item4": "可在路肩停车上下人员",
        "expalins": "只有A最和谐。",
        "url": ""
    },
    {
        "id": 65,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "省道编号",
        "item2": "国道编号",
        "item3": "县道编号",
        "item4": "乡道编号",
        "expalins": "乡道是白底Y字开头的，县道是白底X开头的，省道是黄底的，国道是红底的。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_11.jpg"
    },
    {
        "id": 66,
        "question": "这个标志是何含义？",
        "answer": "4",
        "item1": "小型汽车专用车道",
        "item2": "机动车专用车道",
        "item3": "出租汽车专用车道",
        "item4": "多乘员车辆专用车道",
        "expalins": "此标志为多乘员车辆专用车道，比机动车专用车道标志上的小车多了2个小人，所以它是多乘员车辆专用车道。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_18.jpg"
    },
    {
        "id": 67,
        "question": "发动机起动后仪表板上（如图所示）亮表示什么？",
        "answer": "4",
        "item1": "燃油泵出现异常或者故障",
        "item2": "发动机点火系统出现故障",
        "item3": "发动机供油系统出现异常",
        "item4": "油箱内燃油已到最低液面",
        "expalins": "这个是汽油不足了，多像加油站加油的那个机器，记住机油和汽油是不一样的。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1205.jpeg"
    },
    {
        "id": 68,
        "question": "驾驶机动车在高速公路发生故障，需要停车排除故障时，以下做法先后顺序正确的是？ ①放置警告标志，转移乘车人员至安全处，迅速报警②开启危险报警闪光灯③将车辆移至不妨碍交通的位置④等待救援",
        "answer": "4",
        "item1": "④③①②",
        "item2": "①②③④",
        "item3": "③②①④",
        "item4": "②③①④",
        "expalins": "驾驶机动车在高速公路发生故障，需要停车排除故障时，应当进行如下顺序的操作：开启危险报警闪光灯；将车辆移至不妨碍交通的位置；放置警告标志，转移乘车人员至安全处，迅速报警；等待救援。",
        "url": ""
    },
    {
        "id": 69,
        "question": "这个标志是何含义？",
        "answer": "4",
        "item1": "T型路口",
        "item2": "分流路口",
        "item3": "减速通行",
        "item4": "此路不通",
        "expalins": "用以指示前方道路为死胡同，无出口、不能通行。该标志为蓝底白色街区红色图案。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_219.jpg"
    },
    {
        "id": 70,
        "question": "行车中超越右侧停放的车辆时，为预防其突然起步或开启车门，应怎样做？",
        "answer": "4",
        "item1": "加速通过",
        "item2": "长鸣喇叭",
        "item3": "保持正常速度行驶",
        "item4": "预留出横向安全距离，减速行驶",
        "expalins": "留出安全距离、并减速，万一右侧车辆启动才有足够的空间和时间避让！",
        "url": ""
    },
    {
        "id": 71,
        "question": "路中黄色分界线的作用是什么？",
        "answer": "2",
        "item1": "允许在左侧车道行驶",
        "item2": "分隔对向行驶的交通流",
        "item3": "分隔同向行驶的交通流",
        "item4": "禁止跨越对向行车道",
        "expalins": "分隔相向车道的分界线",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_189.jpg"
    },
    {
        "id": 72,
        "question": "路面上的菱形块虚线是何含义？",
        "answer": "2",
        "item1": "道路施工提示标线",
        "item2": "车行道纵向减速标线",
        "item3": "车行道横向减速标线",
        "item4": "车道变少提示标线",
        "expalins": "车行道纵向减速标线为一组平行于车行道分界线的菱形块虚线。在车行道纵向减速标线的起始位置，设置30 m的渐变段，菱形块虚线由窄变宽－－from 专业控。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_156.jpg"
    },
    {
        "id": 73,
        "question": "下列哪种证件是驾驶机动车上路行驶应当随车携带？",
        "answer": "2",
        "item1": "机动车保险单",
        "item2": "机动车行驶证",
        "item3": "出厂合格证明",
        "item4": "机动车登记证",
        "expalins": "常识题。",
        "url": ""
    },
    {
        "id": 74,
        "question": "机动车在道路上发生故障，需要停车排除时，驾驶人应该怎么办？",
        "answer": "2",
        "item1": "将车停在道路中间",
        "item2": "将车停到不妨碍交通的地方",
        "item3": "开启近光灯或雾灯",
        "item4": "就地停车排除故障",
        "expalins": "只有B最合理，首先应该是不妨碍交通的地方，放在路中间，搞不好后边的看不到撞上来。",
        "url": ""
    },
    {
        "id": 75,
        "question": "危险报警闪光灯可用于下列什么场合？",
        "answer": "3",
        "item1": "遇到道路拥堵时",
        "item2": "在道路上跟车行驶时",
        "item3": "机动车发生故障停车时",
        "item4": "引领后车行驶时",
        "expalins": "危险报警闪光灯是一种提醒其他车辆与行人注意本车发生了特殊情况的信号灯。",
        "url": ""
    },
    {
        "id": 76,
        "question": "遇前方路段车道减少，车辆行驶缓慢，为保证安全有序应该怎样做？",
        "answer": "1",
        "item1": "依次交替通行",
        "item2": "穿插到前方排队车辆中通过",
        "item3": "加速从前车左右超越",
        "item4": "借对向车道迅速通过",
        "expalins": "第五十三条：机动车在车道减少的路口、路段，遇有前方机动车停车排队等候或者缓慢行驶的，应当每车道一辆依次交替驶入车道减少后的路口、路段。",
        "url": ""
    },
    {
        "id": 77,
        "question": "当驾驶车辆行经两侧有行人且有积水的路面时，应怎样做？",
        "answer": "4",
        "item1": "加速通过",
        "item2": "正常行驶",
        "item3": "连续鸣喇叭",
        "item4": "减速慢行",
        "expalins": "常识题，减速可以防止溅水，按喇叭有提醒的作用，但不能防止溅水。 想想我们没车的时候是不是很讨厌那些在积水路面开快车的？好吧，我们还是不要做让别人讨厌的人了吧！",
        "url": ""
    },
    {
        "id": 78,
        "question": "这个标志是何含义？",
        "answer": "2",
        "item1": "漫水桥",
        "item2": "渡口",
        "item3": "船用码头",
        "item4": "过水路面",
        "expalins": "渡口：用以提醒车辆驾驶人谨慎驾驶。设在车辆渡口以前适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_254.jpg"
    },
    {
        "id": 79,
        "question": "这个标志是何含义？",
        "answer": "1",
        "item1": "高速公路紧急停车带",
        "item2": "高速公路避让处所",
        "item3": "高速公路客车站",
        "item4": "高速公路停车区",
        "expalins": "高速公路紧急停车带：用于指示紧急停车的位置，设在紧急停车带的前端。查看高速公路标志大全：http://www.jszks.com/onepage/16721.html",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_183.jpg"
    },
    {
        "id": 80,
        "question": "在这条城市道路上行驶的最高速度不能超过多少？",
        "answer": "3",
        "item1": "30公里/小时",
        "item2": "40公里/小时",
        "item3": "50公里/小时",
        "item4": "70公里/小时",
        "expalins": "根据《中华人民共和国道路交通安全法实施条例》第四十五条：……在没有限速标志、标线的道路上，机动车不得超过下列最高行驶速度：　　(一)没有道路中心线的道路，城市道路为每小时30公里，公路为每小时40公里；　　(二)同方向只有1条机动车道的道路，城市道路为每小时50公里，公路为每小时70公里。图为同方向只有1条机动车道的城市道路，所以最高每小时50公里。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1119.jpg"
    },
    {
        "id": 81,
        "question": "这个标志是何含义？",
        "answer": "3",
        "item1": "省道编号",
        "item2": "县道编号",
        "item3": "乡道编号",
        "item4": "国道编号",
        "expalins": "乡道是白底Y字开头的，县道是白底X开头的，省道是黄底的，国道是红底的。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_131.jpg"
    },
    {
        "id": 82,
        "question": "前轮胎爆裂已出现转向时，驾驶人不要过度矫正，应在控制住方向的情况下，应怎样做，使车辆缓慢减速？",
        "answer": "3",
        "item1": "采取紧急制动",
        "item2": "使用驻车制动",
        "item3": "轻踏制动踏板",
        "item4": "迅速踏下制动踏板",
        "expalins": "A是踩脚刹，B是拉手刹，D是也是踩脚刹，都是属于迅速减速，危险。",
        "url": ""
    },
    {
        "id": 83,
        "question": "这个路面标记是何含义？",
        "answer": "1",
        "item1": "最低限速为80公里/小时",
        "item2": "平均速度为80公里/小时",
        "item3": "最高限速为80公里/小时",
        "item4": "解除80公里/小时限速",
        "expalins": "白色为最低限速，黄色为最高限速。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_250.jpg"
    },
    {
        "id": 84,
        "question": "大雾天行车,多鸣喇叭是为了什么?",
        "answer": "1",
        "item1": "引起对方注意，避免发生危险",
        "item2": "催促前车提速，避免发生追尾",
        "item3": "准备超越前车",
        "item4": "催促前车让行",
        "expalins": "都说了是大雾天，肯定能见度很低啦，所以要靠耳朵来听。多响几声喇叭，就是要告诉别人，这里有车，提高注意！",
        "url": ""
    },
    {
        "id": 85,
        "question": "这个标志是何含义？",
        "answer": "1",
        "item1": "右转车道",
        "item2": "掉头车道",
        "item3": "左转车道",
        "item4": "分向车道",
        "expalins": "表示只准一切车辆向右转弯。此标志设在车辆必须向右转弯的路口以前适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_862.jpg"
    },
    {
        "id": 86,
        "question": "怎样通过这样的路口？",
        "answer": "4",
        "item1": "不减速通过",
        "item2": "加速尽快通过",
        "item3": "空挡滑行通过",
        "item4": "减速或停车观察",
        "expalins": "右侧为无人看守的铁路标志，既然是无人看守，您就得悠着点，减速或停车观察一下吧。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_579.jpg"
    },
    {
        "id": 87,
        "question": "这位驾驶人违反法律规定的行为是什么？",
        "answer": "3",
        "item1": "没按规定握转向盘",
        "item2": "座椅角度不对",
        "item3": "没系安全带",
        "item4": "驾驶姿势不正确",
        "expalins": "这个妹子没系安全带。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_238.jpg"
    },
    {
        "id": 88,
        "question": "驾驶人有哪种情形，交通警察可依法扣留机动车驾驶证？",
        "answer": "4",
        "item1": "超过规定速度10%",
        "item2": "疲劳后驾驶机动车",
        "item3": "行车中未系安全带",
        "item4": "饮酒后驾驶机动车",
        "expalins": "其他的都不足以扣留驾驶证只有D最严重。",
        "url": ""
    },
    {
        "id": 89,
        "question": "机动车在高速公路上发生故障时错误的做法是什么？",
        "answer": "2",
        "item1": "按规定设置警告标志",
        "item2": "车上人员不能下车",
        "item3": "迅速报警",
        "item4": "开启危险报警闪光灯",
        "expalins": "车上的人员应该立即撤到安全栏外。",
        "url": ""
    },
    {
        "id": 90,
        "question": "这个标志是何含义？",
        "answer": "2",
        "item1": "左侧变窄",
        "item2": "窄桥",
        "item3": "窄路",
        "item4": "右侧变窄",
        "expalins": "窄桥：用以警告车辆驾驶人注意前方桥面宽度变窄，应谨慎驾驶。设在桥面净宽较两端路面宽度变窄，且桥的净宽小于6 m的桥梁以前适当位置。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_989.jpg"
    },
    {
        "id": 91,
        "question": "在一般道路倒车时，若发现有过往车辆通过，应怎样做？",
        "answer": "2",
        "item1": "鸣喇叭示意",
        "item2": "主动停车避让",
        "item3": "加速倒车",
        "item4": "继续倒车",
        "expalins": "和谐第一，请立即变身圣人，就知道答案了。",
        "url": ""
    },
    {
        "id": 92,
        "question": "机动车仪表板上（如图所示）亮表示什么？",
        "answer": "2",
        "item1": "前后雾灯开启",
        "item2": "前后位置灯开启",
        "item3": "前照灯开启",
        "item4": "危险报警闪光灯开启",
        "expalins": "位置灯就是车辆示宽灯，也就是当你开启双跳灯后，前后左右四个闪的灯 宽灯就是转向信号灯同时闪烁，用于警告作用。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1108.jpeg"
    },
    {
        "id": 93,
        "question": "这个标志是何含义？",
        "answer": "4",
        "item1": "Y型交叉口",
        "item2": "主路让行",
        "item3": "注意分流",
        "item4": "注意合流",
        "expalins": "黄底为警告标志，所以排除A和B，图很明显的为合流标志，所以选D",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_49.jpg"
    },
    {
        "id": 94,
        "question": "行车中遇有前方发生交通事故，需要帮助时，应怎样做？",
        "answer": "3",
        "item1": "尽量绕道躲避",
        "item2": "立即报警，停车观望",
        "item3": "协助保护现场，并立即报警",
        "item4": "加速通过，不予理睬",
        "expalins": "请伸出您的援手，你不能保证下次需要帮助的人不是你。",
        "url": ""
    },
    {
        "id": 95,
        "question": "泥泞道路对安全行车的主要影响是什么？",
        "answer": "2",
        "item1": "行驶阻力变小",
        "item2": "车轮极易滑转和侧滑",
        "item3": "能见度低，视野模糊",
        "item4": "路面附着力增大",
        "expalins": "泥泞路面特别松软和粘稠，车辆行驶阻力大，附着力减小，车轮极易划转和侧滑。",
        "url": ""
    },
    {
        "id": 96,
        "question": "这属于哪一种标志？",
        "answer": "1",
        "item1": "旅游区标志",
        "item2": "作业区标志",
        "item3": "告示标志",
        "item4": "高速公路标志",
        "expalins": "旅游区方向：设在通往旅游区各连接道路的交叉口处。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1158.jpg"
    },
    {
        "id": 97,
        "question": "驾驶证审验内容不包括以下哪一项？",
        "answer": "4",
        "item1": "道路交通安全违法行为、交通事故处理情况",
        "item2": "身体条件情况",
        "item3": "道路交通安全违法行为记分及记满12分后参加学习和考试情况",
        "item4": "机动车检验情况",
        "expalins": "驾驶证审验内容包括：道路交通安全违法行为、交通事故处理情况；身体条件情况；道路交通安全违法行为记分及记满12分后参加学习和考试情况。",
        "url": ""
    },
    {
        "id": 98,
        "question": "这样在路边临时停放机动车有什么违法行为？",
        "answer": "3",
        "item1": "停车占用机动车道",
        "item2": "距离路边超过30厘米",
        "item3": "在有禁停标线路段停车",
        "item4": "在非机动车道停车",
        "expalins": "图中右侧路边是黄色的禁止停车标线，所以此处是不能停车的。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_225.jpg"
    },
    {
        "id": 99,
        "question": "前方路口这种信号灯亮表示什么意思？",
        "answer": "4",
        "item1": "准许通行",
        "item2": "提醒注意",
        "item3": "路口警示",
        "item4": "禁止通行",
        "expalins": "红灯停。",
        "url": "http://apistore.data.eolinker.com/driver_question/c1c2subject1_1107.jpg"
    },]